# Generated by Django 3.1.2 on 2020-10-18 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('bid', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
