# Generated by Django 3.1.2 on 2020-11-02 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201102_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='listingid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='seller',
        ),
    ]
