# Generated by Django 3.1.2 on 2020-11-02 19:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201102_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='listingid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='seller',
            field=models.CharField(default=datetime.datetime(2020, 11, 2, 19, 8, 26, 161154, tzinfo=utc), max_length=64),
            preserve_default=False,
        ),
    ]
