# Generated by Django 3.1.2 on 2020-11-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201102_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(max_length=64)),
                ('win_price', models.IntegerField()),
                ('title', models.CharField(max_length=64)),
                ('seller', models.CharField(max_length=64)),
                ('listingid', models.IntegerField()),
            ],
        ),
    ]
