# Generated by Django 3.1.2 on 2020-11-05 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20201104_2130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Winner',
        ),
    ]
