# Generated by Django 3.1.2 on 2020-11-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poop', models.CharField(max_length=64)),
            ],
        ),
    ]
