# Generated by Django 3.1.2 on 2020-11-05 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_poop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poop',
        ),
    ]
